feat: Add margin computation APIs
zerodhatech/pykiteconnect pull request #91
Opened 2020-09-30 11:43 UTC by ranjanrak

2020-09-30 12:43 UTC, vijaykz approved these changes

2020-09-30 14:45 UTC, joeirimpan requested changes
@ranjanrak Can you run it through flake8 once? Otherwise looks good to me.

2020-09-30 14:45 UTC, joeirimpan commented on kiteconnect/connect.py
>          "gtt.delete": "/gtt/triggers/{trigger_id}"
missing `,`

2020-10-01 09:58 UTC, ranjanrak commented
Closing this as @vividvilla will add an extra field of url_args to substitute params in the URLs. Also, is_json boolean field for all content-type - application/json body for POST request.

2020-10-01 09:58 UTC, closed without merging